### ISSUE TITLE
Reach Height not being calculated

### ISSUE THREAD

**Issue by duckitron** [geoidesic/foundryvtt-dnd5e-jump-calculator#3]
Hello,

Just installed the module and it's fantastic!  Excited to use it in my games.  I do have one issue when a High Jump is calculated.  Despite entering my character's heights correctly and everything else working, the Reach height is always displayed in chat as `+NaN' NaN"`

I am running on DnD 3.1.2 and Foundry 11 build 315

Thank you and great work!

**Comment by D3natural** [comment]
Hello,
if i set the height to 6 feet and 6 inches it will caluclate correctly since they are round numbers when they half equaling to 3' 3"
 I modified the function to this:

//
function calculateReach(height) {
    // split height string by '.' character
    const split = height.split('.');
    const feet = Number(split[0]);
    const inches = Number(split[1]);
    const halfInches = inches / 2;
    const halfFeet = feet / 2;
    let reachFeet = feet + halfFeet;
    let reachInches = inches + halfInches;
    if(reachInches > 12) {
        reachFeet += 1;
        reachInches -= 12;
    }
    const distance = convertFeetAndInchesToDecimal(reachFeet, reachInches);
    return convertDecimalToFeet(distance);
}
//

if the halfFeet is 2.5 or similar it will give us a NAN value but if we convert the add reachFeet and reachInches  and convert them with a feature convert FeetAndInchestoDecimal it will correctly add what is needed.
i also added 
  const feetRegex = /^(\d{1,2}|\d\s|\d")/gm;
  if one of my players likes to make a more than 10ft character

Regards,
:)

**Comment by duckitron** [comment]
@geoidesic Here are the results I was getting from two different player characters

![JumpHeight1](https://github.com/geoidesic/foundryvtt-dnd5e-jump-calculator/assets/170043641/583e13f2-fee0-466b-b014-310f150a04ff)

![JumpHeight2](https://github.com/geoidesic/foundryvtt-dnd5e-jump-calculator/assets/170043641/cd173900-a037-47fc-a87e-e81e1d781cc7)

I read D3natural's comment and gave one character a rounded 6 feet of height, which ended up working

![JumpHeight3](https://github.com/geoidesic/foundryvtt-dnd5e-jump-calculator/assets/170043641/d23bffa4-d212-4966-8858-fd8d6fc08c54)

**Comment by geoidesic** [comment]
@D3natural @duckitron Thanks for the feedback. I've taken your comments on board. New version will:

- Allow feet or inches to be up to 3 digits long
- Added tests for the edge cases you've mentioned
